name: "CI"
on:
  [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install Linter
        uses: golangci/golangci-lint-action@v3
      - name: Run Linter
        run: make lint
